#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker233"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "5e2c2dff770345c8b5fcefa7190df167" }
]

[assets]
directory = "./public"
